import Vue from 'vue'

Vue.component('Avatar', () => import('./Avatar'))
Vue.component('Dropdown', () => import('./Dropdown'))
Vue.component('FlashMessage', require('./FlashMessage').default)

Vue.component('LoadingSvg', () => import(/* webpackChunkName: "loading" */ './LoadingSvg'))
Vue.component('CardDataLoading', () => import(/* webpackChunkName: "loading" */ './CardDataLoading'))

Vue.component('VIndex', () => import(/* webpackChunkName: "index" */ './VIndex'))
Vue.component('IndexCardTopbar', () => import(/* webpackChunkName: "index" */ './index/IndexCardTopbar'))
Vue.component('IndexNoData', () => import(/* webpackChunkName: "index" */ './index/IndexNoData'))
Vue.component('IndexSearch', () => import(/* webpackChunkName: "index" */ './index/IndexSearch'))
Vue.component('IndexTopbar', () => import(/* webpackChunkName: "index" */ './index/IndexTopbar'))
Vue.component('IndexPagination', () => import(/* webpackChunkName: "index" */ './index/IndexPagination'))
Vue.component('IndexTable', () => import(/* webpackChunkName: "index" */ './index/IndexTable'))
Vue.component('IndexSelectAll', () => import(/* webpackChunkName: "index" */ './index/IndexSelectAll'))
Vue.component('IndexTableSortIcons', () => import(/* webpackChunkName: "index" */ './index/IndexTableSortIcons'))
Vue.component('IndexDeleteRow', () => import(/* webpackChunkName: "index" */ './index/IndexDeleteRow'))
Vue.component('IndexDeleteRows', () => import(/* webpackChunkName: "index" */ './index/IndexDeleteRows'))
Vue.component('IndexTextField', () => import(/* webpackChunkName: "index" */ './index/IndexTextField'))
Vue.component('IndexLinkField', () => import(/* webpackChunkName: "index" */ './index/IndexLinkField'))
Vue.component('IndexLabelField', () => import(/* webpackChunkName: "index" */ './index/IndexLabelField'))
Vue.component('IndexActions', () => import(/* webpackChunkName: "index" */ './index/IndexActions'))
Vue.component('IndexFilters', () => import(/* webpackChunkName: "index" */ './index/IndexFilters'))

Vue.component('VForm', () => import(/* webpackChunkName: "form" */ './VForm'))
Vue.component('FormFields', () => import(/* webpackChunkName: "form" */ './form/FormFields'))
Vue.component('FormTabFields', () => import(/* webpackChunkName: "form" */ './form/FormTabFields'))
Vue.component('FormSubmit', () => import(/* webpackChunkName: "form" */ './form/FormSubmit'))

Vue.component('VDetail', () => import(/* webpackChunkName: "detail" */ './VDetail'))
Vue.component('DataRow', () => import(/* webpackChunkName: "detail" */ './DataRow'))
Vue.component('DetailDelete', () => import(/* webpackChunkName: "detail" */ './detail/DetailDelete'))

Vue.component('VDiv', () => import(/* webpackChunkName: "field" */ './VDiv'))
Vue.component('BaseField', () => import(/* webpackChunkName: "field" */ './fields/BaseField'))
Vue.component('DefaultField', () => import(/* webpackChunkName: "field" */ './fields/DefaultField'))
Vue.component('InlineField', () => import(/* webpackChunkName: "field" */ './fields/InlineField'))
Vue.component('TextField', () => import(/* webpackChunkName: "field" */ './fields/TextField'))
Vue.component('PasswordField', () => import(/* webpackChunkName: "field" */ './fields/PasswordField'))
Vue.component('SelectField', () => import(/* webpackChunkName: "field" */ './fields/SelectField'))
Vue.component('SelectSearchableField', () => import(/* webpackChunkName: "field" */ './fields/SelectSearchableField'))
Vue.component('SelectMultiField', () => import(/* webpackChunkName: "field" */ './fields/SelectMultiField'))
Vue.component('CheckboxField', () => import(/* webpackChunkName: "field" */ './fields/CheckboxField'))
Vue.component('RadioField', () => import(/* webpackChunkName: "field" */ './fields/RadioField'))
Vue.component('BooleanField', () => import(/* webpackChunkName: "field" */ './fields/BooleanField'))
Vue.component('TextareaField', () => import(/* webpackChunkName: "field" */ './fields/TextareaField'))
Vue.component('DateField', () => import(/* webpackChunkName: "field" */ './fields/DateField'))
Vue.component('ConditionalField', () => import(/* webpackChunkName: "field" */ './fields/ConditionalField'))
Vue.component('ImageField', () => import(/* webpackChunkName: "field" */ './fields/ImageField'))
Vue.component('PostField', () => import(/* webpackChunkName: "field" */ './fields/PostField'))

Vue.component('VModal', () => import(/* webpackChunkName: "modal" */ './VModal'))
Vue.component('BaseModal', () => import(/* webpackChunkName: "modal" */ './modal/BaseModal'))
Vue.component('ConfirmModal', () => import(/* webpackChunkName: "modal" */ './modal/ConfirmModal'))
Vue.component('FormModal', () => import(/* webpackChunkName: "modal" */ './modal/FormModal'))

Vue.component('SelectFilter', () => import(/* webpackChunkName: "filter" */ './filters/SelectFilter'))
